import { GraphClient } from '@optimizely/cms-sdk';
import { OptimizelyComponent } from '@optimizely/cms-sdk/react/server';
import { notFound } from 'next/navigation';

/**
 * Controls what happens when a user visits a path that is not generated by `generateStaticParams`
 */
export const dynamicParams = true;

/**
 * Incremental Static Regeneration - regenerate page at most once every 60 seconds
 * This ensures CMS content updates appear on the site within 60 seconds
 */
export const revalidate = 60;

type Props = {
  params: Promise<{
    slug: string[];
  }>;
};

/**
 * Dynamic page route - renders CMS pages based on URL slug
 */
export default async function Page({ params }: Props) {
  const { slug } = await params;

  // Initialize GraphClient
  const client = new GraphClient(process.env.OPTIMIZELY_GRAPH_SINGLE_KEY!, {
    graphUrl: process.env.OPTIMIZELY_GRAPH_GATEWAY,
  });

  // Fetch content by path
  const content = await client.getContentByPath(`/${slug.join('/')}/`);

  // Return 404 if no content found
  if (content.length === 0) {
    notFound();
  }

  // Render the content using OptimizelyComponent
  return <OptimizelyComponent opti={content[0]} />;
}

/**
 * Generates static routes at build-time (optional, for SSG)
 */
export async function generateStaticParams() {
  // Skip static generation if APPLICATION_HOST not set
  if (!process.env.APPLICATION_HOST) {
    return [];
  }

  try {
    const query = `
      query GetPages {
        _Page(limit: 100) {
          items {
            _metadata {
              url {
                base
                default
              }
            }
          }
        }
      }
    `;

    const client = new GraphClient(process.env.OPTIMIZELY_GRAPH_SINGLE_KEY!, {
      graphUrl: process.env.OPTIMIZELY_GRAPH_GATEWAY,
    });

    const data = await client.request(query, {});

    return data._Page.items
      .filter(
        (item: any) => item?._metadata?.url?.base === process.env.APPLICATION_HOST
      )
      .map((item: any) => item?._metadata?.url?.default)
      .filter((path?: string) => typeof path === 'string' && path !== '')
      .map((path: string) => {
        // Remove leading/trailing slashes
        const cleaned = path.replace(/^\/|\/$/g, '');
        return {
          slug: cleaned ? cleaned.split('/') : [],
        };
      });
  } catch (error) {
    console.error('Error generating static params:', error);
    return [];
  }
}
